config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
    # - url: http://loki:3100/loki/api/v1/push
  # snippets:
  #   extraScrapeConfigs: |
  #     - job_name: kubernetes-pods
  #       kubernetes_sd_configs:
  #         - role: pod
  #       relabel_configs:
  #         - source_labels: [__meta_kubernetes_pod_node_name]
  #           target_label: node
  #         - source_labels: [__meta_kubernetes_namespace]
  #           target_label: namespace
  #         - source_labels: [__meta_kubernetes_pod_name]
  #           target_label: pod
  #         - source_labels: [__meta_kubernetes_pod_container_name]
  #           target_label: container
  #         - action: labelmap
  #           regex: __meta_kubernetes_pod_label_(.+)

daemonset:
  enabled: true