secret:
    username: ENC[AES256_GCM,data:dWx6MCc=,iv:yeGAm1bz5xB1Psk1GqHMOq9Qtz7/Fvftrn8zp2aBtSc=,tag:ud0DTlX1fNZJ/tYcFbJlwg==,type:str]
    password: ENC[AES256_GCM,data:uUznWuOvYu0ufsLxG8xHonNpnM4=,iv:MlKKhbGMK5kmWM0W5bOm9Icv9SDAoYlYNzBH5ksxn0c=,tag:hwrHoVFJN2f6hutLvAdTpg==,type:str]
sops:
    lastmodified: "2025-11-25T19:34:55Z"
    mac: ENC[AES256_GCM,data:2ezck11hn7K01jVgdJuu59Gr8W7ohvZcDRok9lLshpEgL6NB6hcryZRwh3px6vIG9TAyl4xq0ADWcqsshOkBYtI/hi94XmEcmOOgSvHvxkmiKeSXsYtu8hbDEWT/dyjRvm8yaoRsV+hjKgNAgFl5w6y/MvTe93TLRskKiT3dn40=,iv:nypa4GK6UiDdrZAnhVQWJzNYUeBdPxeELycDuYMI6EA=,tag:zdYDs7z7KwJ8U+9pr27d0Q==,type:str]
    pgp:
        - created_at: "2025-11-25T18:52:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0luRrROEc2WAQ/6Azyd6ppGmh34H9FYcgUS9s8qIlH2cIwOaoZ3/AzmBOWa
            Ucsr9vN3CIhF3tTtXE/ndkD6mtioka6xT65glbi7HYCe55asxasZDdbzrVQFLxgQ
            mJjJSrSlahHpVMYu3K7OgIAQ3sjMjhyng2Jgk92FSizUXHElQW/Ijdu7JrOxFvRG
            PhpVDGNPKoXqdCyj+xKZp8BCYi6Inf8CxzrurnOb/CifWxBGNYvOtj/VOiCrQDl8
            sBWAPzpz3JHvhA/wiP+PMqFxHfYBfVHlgZlsr8Hu4K07Zp687BrKrZ8cTnXdcTJl
            eO7bW2XBnnLIRJjZ/GVGrZU9U+2tVyFO+X0nPUOghhwPWcrdkXgOAHpRv5xqAWBE
            wC4CzmJJ1XhlyQim5H4uUV9alyv9K4OYQM/VUcTy41a8nar+7g3FBGkr+yr9bx1F
            +jZl6g4usnkTQJq9vYznLFoORu+c04lip8W4XlCNd2H4NmoZWyvX4IUCEbJSGm7G
            1r7cjHyu4Q21Tr/Qi3Loum4UiAjZaCKHlD7TRj3x6L1YJkohGrHzWXRpG8L2CpI3
            P7MOylrae+ZlV86HyobvFLsZ82c9RgLhyimYocRbl3MbVr6fPxW1TlOyoNusDYpw
            DH4oUuHsTnYJyfQwwEIXXpG4lJRsFz7N8xkjne5ysGC5Om7k2BqwR/bpkTEXhVjU
            aAEJAhBMp3ekZzTtOTSvWgFUr2VbSCjJhH2PCBG670xfHgM7UUt225T2vhIgNuMc
            WaloF6/8V6vnHmVeLBxGkUgKa56KhFmsCC3UM00X/+ouvLDWGyWeVpC5fs4kPRJG
            5UfJmq7Wh1Od
            =5yqc
            -----END PGP MESSAGE-----
          fp: B97A7942D212DDCE7AE6B8E751A654CDAC3EE761
    unencrypted_suffix: _unencrypted
    version: 3.10.2
